"use client";
import {useAdmin} from './language';
import {metricCounts,mostRequested} from '../analytics';
export function AnalyticsPanel({s}:{s:any}) {
 const t=useAdmin(),o=s.operations,m=metricCounts(o.metrics),a=o.analytics||{},count=(key:string)=>m[key]||0;
 const rows=(items:[string,string,string][])=> <dl className="analytics-counts">{items.map(([key,pt,en])=><div key={key}><dt>{t(pt,en)}</dt><dd>{count(key)}</dd></div>)}</dl>;
 const top=mostRequested(s.ranking||[]),views=Object.entries(m).filter(([key])=>key.startsWith('view:')).reduce((sum,[,n])=>sum+n,0);
 return <section id="analytics"><p className="eyebrow">{t('DEPOIS DA ÚLTIMA NOTA','AFTER THE LAST NOTE')}</p><h2>{t('O alcance deste evento','Event activity')}</h2><h3>{s.session.name}</h3><p className="hint">{t('Muda o evento em Eventos. Contagens agregadas, não pessoas únicas. Sem cookies de analytics ou perfis pessoais.','Change the event in Events. Aggregate counts, not unique people. No analytics cookies or personal profiles.')}</p>
 {a.period?.first&&<p>{t('Dias com registos (UTC)','Days with records (UTC)')}: {a.period.first} → {a.period.last}</p>}
 <div className="metric-grid"><div><strong>{views}</strong><span>{t('Visualizações de páginas','Page views')}</span></div><div><strong>{count('view:/')}</strong><span>{t('Visualizações da página LIVE','LIVE page views')}</span></div><div><strong>{count('request')}</strong><span>{t('Pedidos registados no contador','Requests recorded by the counter')}</span></div></div>
 {rows([['qr_open','Aberturas por link do evento','Event link opens']])}
 <h3>{t('As 5 músicas mais pedidas','The 5 most requested songs')}</h3>{top.length?<ol className="analytics-songs">{top.map(r=><li key={r.key}><span><strong>{r.title}</strong> {r.artist}</span><b>{r.organic}</b></li>)}</ol>:<p>{t('Ainda sem pedidos guardados.','No retained requests yet.')}</p>}<p className="hint">{t('Pedidos efetivos guardados, sem votos de tips. Retenção de pedidos: 90 dias; contadores: 365 dias. Os totais podem diferir.','Retained actual requests, excluding tip votes. Requests are retained for 90 days; counters for 365 days. Totals may differ.')}</p>
 <h3>{t('Cliques para continuar a ouvir','Clicks to keep listening')}</h3>{rows([['click:spotify','Spotify','Spotify'],['click:instagram','Instagram','Instagram'],['click:youtube','YouTube','YouTube'],['click:twitch','Twitch','Twitch'],['click:discord','Discord','Discord'],['click:whatsapp','WhatsApp','WhatsApp'],['click:featured-original','Original em destaque · ouvir','Featured original · listen'],['click:projects','Descobrir projetos','Discover projects'],['click:project:pedro','Projeto Pedro Melo','Pedro Melo project'],['click:project:giants','Projeto Giant’s Magazine','Giant’s Magazine project'],['click:project:pete','Projeto Pete On The Radio','Pete On The Radio project']])}
 <h3>{t('Aulas e comunidade','Lessons & community')}</h3>{rows([['view:/aulas','Visualizações de aulas','Lesson page views'],['click:lessons','Cliques para aulas','Clicks to lessons'],['view:/comunidade','Visualizações da comunidade','Community page views'],['click:community','Ficar por perto · cliques','Stay connected · clicks'],['consent:email','Consentimentos iniciados · email','Consent registrations · email'],['consent:whatsapp','Consentimentos iniciados · WhatsApp','Consent registrations · WhatsApp']])}
 <p>{t('Contactos com consentimento válido atualmente','Contacts with currently valid consent')}: <b>{a.contacts?.active||0}</b> · {t('Verificados','Verified')}: <b>{a.contacts?.confirmed||0}</b></p><p className="hint">{t('São registos de contacto, não pessoas únicas nem conversas. As confirmações refletem apenas os registos ainda válidos e guardados.','These are contact records, not unique people or conversations. Confirmations reflect only retained, currently valid records.')}</p>
 <h3>{t('Apoio à música','Supporting the music')}</h3>{rows([['view:/apoio','Visualizações de apoio','Support page views'],['click:support','Cliques para deixar tip','Clicks to leave a tip']])}<p>{t('Tips declaradas neste evento','Tips declared for this event')}: <b>{a.tips?.declared||0}</b> · {t('Pendentes','Pending')}: <b>{a.tips?.pending||0}</b> · {t('Confirmadas','Confirmed')}: <b>{a.tips?.confirmed||0}</b></p><p>{t('Recebido confirmado, descontando reembolsos','Confirmed receipts less refunds')}: <b>{((a.tips?.netCents||0)/100).toFixed(2)} €</b></p>
 <p className="hint">{t('Cliques não garantem audições, contactos ou pagamentos. Não há funil individual nem taxa de conversão: as ações não estão ligadas entre si. Novos CTAs só contam a partir do Bloco G; zero significa nenhum registo, não prova de ausência de atividade. Falhas de rede podem perder contagens.','Clicks do not guarantee listens, contacts or payments. No individual funnel or conversion rate: actions are not linked. New CTA tracking starts with Block G; zero means no records, not proof of no activity. Network failures can lose counts.')}</p>
 </section>;
}
