"use client";
import {useEffect,useRef,useState} from 'react';
import {useAdmin} from './language';
import {photoSlots, type PhotoSlot} from '../photography';
function PhotoEditor({slot}:{slot:PhotoSlot}) {
  const t=useAdmin(),lock=useRef(false),[busy,B]=useState(false),[image,I]=useState<string|null>(null),[state,S]=useState('loading'),[revision,R]=useState(0);
  useEffect(()=>{let alive=true,url='';S('loading');I(null);fetch('/api/project-photo?slot='+slot,{cache:'no-store'}).then(async r=>{if(r.status===404){if(alive)S('empty');return;}if(!r.ok)throw Error();url=URL.createObjectURL(await r.blob());if(alive){I(url);S('ready');}else URL.revokeObjectURL(url);}).catch(()=>{if(alive)S('error');});return()=>{alive=false;if(url)URL.revokeObjectURL(url);};},[slot,revision]);
  async function save(file?:File){if(lock.current)return;if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1024*1024)){S('invalid');return;}if(!file&&!confirm(t('Remover esta fotografia?','Remove this photograph?')))return;lock.current=true;B(true);try{const r=await fetch('/api/project-photo?slot='+slot,{method:file?'PUT':'DELETE',headers:file?{'Content-Type':file.type}:undefined,body:file});if(!r.ok)throw Error();R(v=>v+1);}catch{S('error');}finally{lock.current=false;B(false);}}
  return <fieldset className="photo-editor" disabled={busy||state==='loading'}><legend>{slot==='home'?t('Assinatura da Home','Home signature'):slot==='pedro'?'Pedro Melo':slot==='giants'?'Giant’s Magazine':'Pete On The Radio'}</legend>{image&&<img src={image} alt={t('Fotografia guardada','Saved photograph')}/>}<label>{t('Carregar ou substituir · JPG, PNG, WebP · até 1 MB','Upload or replace · JPG, PNG, WebP · up to 1 MB')}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void save(file);}}/></label><div className="row">{image&&<button type="button" onClick={()=>void save()}>{t('Remover fotografia','Remove photograph')}</button>}{state==='error'&&<button type="button" onClick={()=>R(v=>v+1)}>{t('Tentar novamente','Try again')}</button>}</div><p className="photo-feedback" role="status">{busy?t('A guardar…','Saving…'):state==='loading'?t('A carregar…','Loading…'):state==='error'?t('Não foi possível concluir. Tenta novamente.','Could not complete. Please try again.'):state==='invalid'?t('Escolhe JPG, PNG ou WebP até 1 MB.','Choose JPG, PNG or WebP up to 1 MB.'):state==='empty'?t('Sem fotografia. O layout funciona sem imagem.','No photograph. The layout works without an image.'):t('Fotografia guardada.','Photograph saved.')}</p></fieldset>;
}
export function PhotographyPanel(){const t=useAdmin();return <section><h2>{t('Fotografias dos projetos','Project photography')}</h2><p>{t('Opcionais e públicas. Carrega apenas imagens que possas partilhar.','Optional and public. Only upload images you can share.')}</p>{photoSlots.map(slot=><PhotoEditor key={slot} slot={slot}/>)}</section>;}
