import {tipsFor,tipCommand} from '../../tips';
import {siteContent,contentCommand} from '../../content';
import {admin,db,provision,sessionById,sessionState,sessionSongs,activeId,allSongs,links,json,save,sameOrigin,reportError} from '../../data';
import {operationsState,copySetlist,maintenance,enqueueQueries,eventUrl} from '../../operations';
import {dispatch} from '../../integration-delivery';
import {defaultLinks} from '../../catalog';
import {sessionCommand} from '../../session-commands';
import {importSongs,songKey} from '../../import-songs';
import {requestPage,ranking,InputError} from '../../request-pages';
export async function GET(r:Request){try{if(!await admin())return json({error:'forbidden'},403);await provision();const u=new URL(r.url),active=await activeId(),id=u.searchParams.get('sessionId')||active||'session-initial';if(u.searchParams.get('view')==='export'){if(id!=='all'&&!await sessionById(id))return json({error:'missing_session'},404);return json(await requestPage(id,u.searchParams.get('cursor')))}const state=await sessionState(id);if(!state)return json({error:'missing_session'},404);const [songs,sessions,page,rank]=await Promise.all([sessionSongs(id),db().prepare('SELECT id,name,date,mode,revision,archived,created FROM sessions ORDER BY created DESC,id').all(),requestPage(id),ranking(id)]);return json({...state,activeSessionId:active,settings:{...await links(),requestsOpen:!!state.session.requestsOpen},songs,sessions:sessions.results,requests:page.requests,requestPage:{nextCursor:page.nextCursor,total:page.total,snapshot:page.snapshot},ranking:rank,operations:await operationsState(id),content:await siteContent(),tips:await tipsFor(id)})}catch(e){if(e instanceof InputError)return json({error:e.message},400);reportError('GET /api/manage',e);return json({error:'unavailable'},503)}}
export async function POST(r:Request){if(!sameOrigin(r))return json({error:'origin'},403);try{if(!await admin())return json({error:'forbidden'},403);const raw=await r.text();if(raw.length>600000)return json({error:'size'},413);let b:any;try{b=JSON.parse(raw)}catch{return json({error:'invalid'},400)}await provision();if(!b||typeof b.action!=='string')return json({error:'invalid'},400);if(b.action==='maintenance'){await maintenance(true);return json({ok:true})}if(b.action==='dispatch')return json({ok:true,...await dispatch()});const tip=await tipCommand(b);if(tip)return tip;const content=await contentCommand(b);if(content)return content;const copied=await copySetlist(b);if(copied)return copied;const handled=await sessionCommand(b);if(handled){if(handled.ok&&b.action==='song_state'&&b.status==='playing'){const state=await sessionState(b.sessionId);if(state){const queries=enqueueQueries('now_playing',{sessionId:b.sessionId,song:state.now.song,artist:state.now.artist,url:eventUrl(b.sessionId)},b.sessionId+':'+state.session.revision);if(queries.length)await db().batch(queries)}}return handled;}if(['import_preview','import_commit'].includes(b.action))return importSongs(b);const d=db();
if(b.action==='song_save'){const s=b.song;if(!s||typeof s.title!=='string'||!s.title.trim()||s.title.length>140||typeof s.artist!=='string'||!s.artist.trim()||s.artist.length>140||typeof s.lyrics!=='string'||s.lyrics.length>30000||typeof s.lyricsApproved!=='boolean')return json({error:'invalid'},400);const catalog=await allSongs();if(catalog.some((row:any)=>row.id!==s.id&&songKey(row.title,row.artist)===songKey(s.title,s.artist)))return json({error:'duplicate_song'},409);if(s.id){if(typeof s.id!=='string'||!Number.isInteger(s.revision))return json({error:'invalid'},400);const result=await d.prepare('UPDATE songs SET title=?,artist=?,lyrics=?,lyrics_approved=?,revision=revision+1 WHERE id=? AND revision=?').bind(s.title.trim(),s.artist.trim(),s.lyrics,s.lyricsApproved?1:0,s.id,s.revision).run();if(!result.meta.changes)return json({error:'conflict'},409)}else{const session=await sessionById(b.sessionId||'');if(!session||session.archived||session.revision!==b.sessionRevision)return json({error:'conflict'},409);const id=crypto.randomUUID();const queries=[d.prepare('INSERT INTO songs(id,title,artist,lyrics,lyrics_approved) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM sessions WHERE id=? AND revision=?)').bind(id,s.title.trim(),s.artist.trim(),s.lyrics,s.lyricsApproved?1:0,session.id,session.revision),d.prepare('INSERT INTO session_songs(session_id,song_id,position) SELECT ?,id,rowid FROM songs WHERE id=?').bind(session.id,id),d.prepare('UPDATE sessions SET revision=revision+1 WHERE id=? AND revision=?').bind(session.id,session.revision)];const result=await d.batch(queries);if(!result.at(-1)?.meta.changes)return json({error:'conflict'},409)}}
else if(b.action==='links'){const out:Record<string,string>={};for(const key of Object.keys(defaultLinks)){const v=b.links?.[key];if(typeof v!=='string'||v.length>2000||(v&&!/^https:\/\//.test(v)))return json({error:'invalid'},400);if(v){const u=new URL(v);if(u.username||u.password)return json({error:'invalid'},400)}if(key==='whatsapp'&&/wa\.me\/\d/.test(v))return json({error:'username_required'},400);out[key]=v}await save('links',out)}else return json({error:'invalid'},400);return json({ok:true})}catch(e){reportError('POST /api/manage',e);return json({error:'unavailable'},503)}}
