import {env} from 'cloudflare:workers';
import {db} from './data';
import {hash} from './operations';
import {validateBackup} from './backup-schema';
const bucket=()=> (env as any).BUCKET as R2Bucket;
export async function consistentBackup(){const d=db();await d.prepare('INSERT OR IGNORE INTO database_revision(id,revision) VALUES (1,0)').run();const definitions=[['songs','*',2000],['sessions','*',500],['session_songs','*',25000],['requests','id,song,song_id AS songId,session_id AS sessionId,name,created,status',25000],['metrics','*',25000],['tips','*',10000]] as const;const result=await d.batch([d.prepare('SELECT revision FROM database_revision WHERE id=1'),...definitions.map(([table,columns,limit])=>d.prepare('SELECT '+columns+' FROM '+table+' ORDER BY rowid LIMIT '+(limit+1))),d.prepare("SELECT key,value FROM settings WHERE key IN ('links','active_session','site_content') ORDER BY key")]);const out:any={version:'0.6',complete:true,snapshot:Date.now(),consistency:'transaction',revision:(result[0].results[0] as any).revision};definitions.forEach(([key,,limit],i)=>{if(result[i+1].results.length>limit)throw Error('Snapshot too large');out[key]=result[i+1].results});out.settings=result.at(-1)!.results;out.count=out.requests.length;const text=JSON.stringify(out);if(new TextEncoder().encode(text).length>8*1024*1024)throw Error('Snapshot exceeds 8 MiB');return {data:out,text}}
export async function previewRestore(raw:string){const backup=validateBackup(JSON.parse(raw));const current=await consistentBackup();const id=crypto.randomUUID(),sourceKey='restore/'+id+'/source.json',safetyKey='restore/'+id+'/before.json';await bucket().put(sourceKey,JSON.stringify(backup));await bucket().put(safetyKey,current.text);const summary={incoming:{songs:backup.songs.length,sessions:backup.sessions.length,requests:backup.requests.length,tips:backup.tips.length},current:{songs:current.data.songs.length,sessions:current.data.sessions.length,requests:current.data.requests.length,tips:current.data.tips.length},names:backup.sessions.map(v=>v.name),hasContent:backup.settings.some(v=>v.key==='site_content')};await db().prepare('INSERT INTO restore_jobs(id,base_revision,source_key,safety_key,hash,summary,expires) VALUES (?,?,?,?,?,?,?)').bind(id,current.data.revision,sourceKey,safetyKey,await hash(JSON.stringify(backup)),JSON.stringify(summary),Date.now()+86400000).run();return {id,summary,expires:Date.now()+86400000}}
export async function applyRestore(id:string){const d=db();const job=await d.prepare('SELECT * FROM restore_jobs WHERE id=? AND expires>?').bind(id,Date.now()).first<any>();if(!job)throw Error('Missing preview');if(job.applied===2)return {ok:true,alreadyApplied:true};const object=await bucket().get(job.source_key);if(!object)throw Error('Missing backup');const raw=await object.text();if(await hash(raw)!==job.hash)throw Error('Backup changed');const b=validateBackup(JSON.parse(raw));const nonce=crypto.randomUUID(),guard='EXISTS(SELECT 1 FROM restore_jobs WHERE id=? AND applied=1 AND nonce=?)',bind=[id,nonce],queries:D1PreparedStatement[]=[d.prepare("UPDATE restore_jobs SET applied=1,nonce=? WHERE id=? AND applied=0 AND base_revision=(SELECT revision FROM database_revision WHERE id=1) AND NOT EXISTS(SELECT 1 FROM export_jobs WHERE state='pending' AND expires>?)").bind(nonce,id,Date.now())];
for(const table of ['session_songs','requests','tips','metrics','sessions','songs'])queries.push(d.prepare('DELETE FROM '+table+' WHERE '+guard).bind(...bind));
function insert(table:string,rows:any[],columns:string[],mapping=columns){let chunk:any[]=[],size=0;function flush(){if(!chunk.length)return;queries.push(d.prepare('INSERT INTO '+table+'('+columns.join(',')+') SELECT '+mapping.map(k=>k==='_empty'?"''":"json_extract(value,'$."+k+"')").join(',')+' FROM json_each(?) WHERE '+guard).bind(JSON.stringify(chunk),...bind));chunk=[];size=0}for(const row of rows){const n=new TextEncoder().encode(JSON.stringify(row)).length;if(size+n>150000)flush();chunk.push(row);size+=n}flush()}
insert('songs',b.songs,['id','title','artist','status','lyrics','lyrics_approved','revision','genre','decade','language','mood','recommended']);insert('sessions',b.sessions,['id','name','date','mode','created','requests_open','now_song_id','archived','revision','venue','city','featured_title','featured_artist','featured_url']);insert('session_songs',b.session_songs,['session_id','song_id','status','in_setlist','position']);insert('requests',b.requests,['id','song','song_id','session_id','name','created','status','client'],['id','song','songId','sessionId','name','created','status','_empty']);insert('metrics',b.metrics,['day','session_id','event','count']);insert('tips',b.tips,['id','session_id','request_id','song_id','provider','expected_cents','received_cents','refunded_cents','paid_votes','state','external_ref','created','revision']);
queries.push(d.prepare("DELETE FROM settings WHERE key IN ('links','active_session','site_content') AND "+guard).bind(...bind));insert('settings',b.settings,['key','value']);queries.push(d.prepare("DELETE FROM outbox WHERE event='now_playing' AND "+guard).bind(...bind));queries.push(d.prepare('UPDATE restore_jobs SET applied=2 WHERE id=? AND nonce=? AND applied=1').bind(...bind));const result=await d.batch(queries);return result.at(-1)?.meta.changes?{ok:true}:{ok:false,error:'conflict'} }
export async function cleanupRestores(){const d=db(),jobs=(await d.prepare('SELECT * FROM restore_jobs WHERE expires<? LIMIT 5').bind(Date.now()).all<any>()).results;for(const job of jobs){await bucket().delete([job.source_key,job.safety_key]);await d.prepare('DELETE FROM restore_jobs WHERE id=?').bind(job.id).run()}}
