import {songMetadataShape,eventMetadataShape,eventMetadataSchema} from './music-metadata';
import {validateContent} from './content';
import {z} from 'zod';
import {defaultLinks} from './catalog';
const id=z.string().min(1).max(100),integer=z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),text=z.string();
const song=z.object({...songMetadataShape,id,title:text.min(1).max(140),artist:text.min(1).max(140),status:z.enum(['available','reserved','playing','played','hidden']).default('available'),lyrics:text.max(30000).default(''),lyrics_approved:z.number().int().min(0).max(1).default(0),revision:integer.default(0)});
const session=z.object({...eventMetadataShape,id,name:text.min(1).max(100),date:text.max(10).default(''),mode:z.enum(['concert','busking','twitch']).default('concert'),created:integer,requests_open:z.number().int().min(0).max(1),now_song_id:id.nullable().default(null),archived:z.number().int().min(0).max(1),revision:integer});
const membership=z.object({session_id:id,song_id:id,status:z.enum(['available','reserved','playing','played','hidden']),in_setlist:z.number().int().min(0).max(1),position:integer});
const request=z.object({id,song:text.max(400),songId:id.nullable(),sessionId:id.nullable(),name:text.max(60),created:integer,status:z.enum(['pending','played'])});
const tip=z.object({id,session_id:id.nullable(),request_id:id.nullable(),song_id:id.nullable(),provider:z.enum(['paypal','revolut','mbway']),expected_cents:integer.max(100000),received_cents:integer.max(100000),refunded_cents:integer.max(100000),paid_votes:z.number().int().min(0).max(1),state:z.enum(['pending','confirmed','refunded','rejected']),external_ref:text.max(140).nullable(),created:integer,revision:integer});
export const backupSchema=z.object({version:z.enum(['0.4','0.5','0.6']),complete:z.literal(true),songs:z.array(song).max(2000),sessions:z.array(session).max(500),session_songs:z.array(membership).max(25000),requests:z.array(request).max(25000),metrics:z.array(z.object({day:text.regex(/^\d{4}-\d{2}-\d{2}$/),session_id:id,event:text.max(80),count:integer})).max(25000),settings:z.array(z.object({key:z.enum(['links','active_session','site_content']),value:text.max(100000)})).max(3),tips:z.array(tip).max(10000).default([]),count:integer});
export function validateBackup(input:unknown){const b=backupSchema.parse(input);for(const session of b.sessions)eventMetadataSchema.parse(session);if(b.count!==b.requests.length)throw Error('Request count mismatch');const unique=(a:any[],key:(v:any)=>string)=>{const values=a.map(key);if(new Set(values).size!==values.length)throw Error('Duplicate identifiers')};for(const list of [b.songs,b.sessions,b.requests,b.tips])unique(list,v=>v.id);unique(b.session_songs,v=>v.session_id+':'+v.song_id);unique(b.metrics,v=>v.session_id+':'+v.day+':'+v.event);unique(b.settings,v=>v.key);const songs=new Set(b.songs.map(v=>v.id)),sessions=new Set(b.sessions.map(v=>v.id)),requests=new Set(b.requests.map(v=>v.id));if(!sessions.size||!songs.size)throw Error('Empty catalogue or sessions');const has=(set:Set<string>,id:string|null)=>id===null||set.has(id);for(const v of b.session_songs)if(!songs.has(v.song_id)||!sessions.has(v.session_id))throw Error('Broken setlist reference');for(const r of b.requests)if(!has(songs,r.songId)||!has(sessions,r.sessionId))throw Error('Broken request reference');for(const v of b.sessions)if(v.now_song_id&&(!songs.has(v.now_song_id)||!b.session_songs.some(x=>x.session_id===v.id&&x.song_id===v.now_song_id&&x.status==='playing')))throw Error('Broken now playing');for(const v of b.metrics)if(!sessions.has(v.session_id))throw Error('Broken metric reference');for(const v of b.tips)if(!has(songs,v.song_id)||!has(sessions,v.session_id)||v.refunded_cents>v.received_cents||(v.state==='confirmed'&&(!v.external_ref||v.received_cents<1)))throw Error('Invalid payment record');unique(b.tips.filter(v=>v.external_ref),v=>v.provider+':'+v.external_ref!.toLowerCase());
if(!b.settings.some(v=>v.key==='active_session'))throw Error('Missing active session setting');for(const v of b.sessions){const playing=b.session_songs.filter(x=>x.session_id===v.id&&x.status==='playing');if(playing.length>1||playing.some(x=>x.song_id!==v.now_song_id))throw Error('Inconsistent playback state')}
for(const setting of b.settings){const value=JSON.parse(setting.value);if(setting.key==='active_session'&&!has(sessions,value))throw Error('Invalid active session');if(setting.key==='links'){for(const [k,v] of Object.entries(value)){if(!(k in defaultLinks)||typeof v!=='string'||v.length>2000)throw Error('Invalid links');if(v){const u=new URL(v);if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid link URL')}}}if(setting.key==='site_content'&&validateContent(value) instanceof Response)throw Error('Invalid content')}
return b}
