import {db,json,save} from './data';
import {projectDefaults} from './project-defaults';
export async function siteContent(){const row=await db().prepare("SELECT value FROM settings WHERE key='site_content'").first<{value:string}>();const saved=row?JSON.parse(row.value):{};return {...projectDefaults,...saved,payments:{...projectDefaults.payments,...saved.payments}}}
export function validateContent(c:any){if(!c||typeof c!=='object')return json({error:'invalid'},400);const out:any={};for(const k of ['pedro','giants','pete']){if(!c[k]||['bioPT','bioEN'].some(f=>typeof c[k][f]!=='string'||c[k][f].length>4000))return json({error:'invalid'},400);out[k]={bioPT:c[k].bioPT.trim(),bioEN:c[k].bioEN.trim()}}
if(!Array.isArray(c.shows)||c.shows.length>100)return json({error:'invalid'},400);const ids=new Set();out.shows=[];for(const s of c.shows){if(!s||typeof s.id!=='string'||ids.has(s.id)||s.id.length>80||typeof s.title!=='string'||!s.title.trim()||s.title.length>140||!/^\d{4}-\d{2}-\d{2}$/.test(s.date)||isNaN(Date.parse(s.date))||new Date(s.date).toISOString().slice(0,10)!==s.date||!['pedro','giants','pete'].includes(s.project)||['venue','city'].some(k=>typeof s[k]!=='string'||s[k].length>140)||typeof s.url!=='string'||s.url.length>2000)return json({error:'invalid'},400);if(s.url&&!https(s.url))return json({error:'invalid'},400);ids.add(s.id);out.shows.push({id:s.id,title:s.title.trim(),date:s.date,venue:s.venue,city:s.city,url:s.url,project:s.project})}
if(!Array.isArray(c.instagramPosts)||c.instagramPosts.length>6||c.instagramPosts.some((v:any)=>typeof v!=='string'||!/^https:\/\/(www\.)?instagram\.com\/(p|reel)\/[A-Za-z0-9_-]+\/?$/.test(v)))return json({error:'invalid'},400);out.instagramPosts=c.instagramPosts;
const p=c.payments;if(!p||typeof p.enabled!=='boolean'||typeof p.paidVotes!=='boolean'||['paypal','revolut','mbway'].some(k=>typeof p[k]!=='string'||p[k].length>2000))return json({error:'invalid'},400);if(p.paypal&&!safePayment(p.paypal,'paypal'))return json({error:'payment_url'},400);if(p.revolut&&!safePayment(p.revolut,'revolut'))return json({error:'payment_url'},400);if(p.mbway&&!(https(p.mbway)&&new URL(p.mbway).hostname==='tipme.to'))return json({error:'invalid'},400);if(p.enabled&&!p.paypal&&!p.revolut&&!p.mbway)return json({error:'payment_url'},400);out.payments={paypal:p.paypal,revolut:p.revolut,mbway:p.mbway,enabled:p.enabled,paidVotes:p.paidVotes};return out}
export async function contentCommand(b:any){if(b.action!=='content_save')return null;const result=validateContent(b.content);if(result instanceof Response)return result;await save('site_content',result);return json({ok:true})}
function https(raw:string){try{const u=new URL(raw);return u.protocol==='https:'&&!u.username&&!u.password}catch{return false}}
function safePayment(raw:string,provider:string){if(!https(raw))return false;const u=new URL(raw);return provider==='paypal'?['paypal.me','www.paypal.com','paypal.com'].includes(u.hostname):['revolut.me','pay.revolut.com'].includes(u.hostname)}
