import {env} from 'cloudflare:workers';
import {getChatGPTUser} from './chatgpt-auth';
import {defaultLinks,initialSongs} from './catalog';
export function db(){const d=(env as any).DB as D1Database;if(!d)throw Error('Database unavailable');return d}
export async function provision(){const d=db();if(!await d.prepare("SELECT key FROM settings WHERE key='catalog_v02_initialized'").first())await d.batch([...initialSongs.map(s=>d.prepare("INSERT OR IGNORE INTO songs(id,title,artist) SELECT ?,?,? WHERE NOT EXISTS(SELECT 1 FROM settings WHERE key='catalog_v02_initialized')").bind(s.id,s.title,s.artist)),d.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES ('catalog_v02_initialized','true')")]);
if(!await d.prepare("SELECT key FROM settings WHERE key='sessions_v03_initialized'").first())await d.batch([
 d.prepare("INSERT OR IGNORE INTO sessions(id,name,created,requests_open,now_song_id) SELECT 'session-initial','Concerto inicial',?,CASE WHEN EXISTS(SELECT 1 FROM settings WHERE key='requestsOpen' AND value='false') THEN 0 ELSE 1 END,(SELECT json_extract(value,'$.songId') FROM settings WHERE key='now') WHERE NOT EXISTS(SELECT 1 FROM settings WHERE key='sessions_v03_initialized')").bind(Date.now()),
 d.prepare("INSERT OR IGNORE INTO session_songs(session_id,song_id,status,in_setlist,position) SELECT 'session-initial',id,status,CASE WHEN status IN ('reserved','playing') THEN 1 ELSE 0 END,rowid FROM songs WHERE NOT EXISTS(SELECT 1 FROM settings WHERE key='sessions_v03_initialized')"),
 d.prepare("UPDATE requests SET session_id='session-initial' WHERE session_id IS NULL AND NOT EXISTS(SELECT 1 FROM settings WHERE key='sessions_v03_initialized')"),
 d.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES ('active_session','\"session-initial\"')"),
 d.prepare("INSERT OR IGNORE INTO settings(key,value) VALUES ('sessions_v03_initialized','true')")]);}
export async function sessionById(id:string){const row=await db().prepare('SELECT id,name,date,mode,created,requests_open AS requestsOpen,now_song_id AS nowSongId,archived,revision FROM sessions WHERE id=?').bind(id).first<any>();return row?{...row,venue:'',city:'',featuredTitle:'',featuredArtist:'',featuredUrl:''}:null}
export async function activeId(){const row=await db().prepare("SELECT value FROM settings WHERE key='active_session'").first<{value:string}>();return row?JSON.parse(row.value):null}
export async function sessionSongs(id:string){return (await db().prepare('SELECT s.id,s.title,s.artist,s.lyrics,s.lyrics_approved AS lyricsApproved,s.revision,ss.status,ss.in_setlist AS inSetlist,ss.position FROM session_songs ss JOIN songs s ON s.id=ss.song_id WHERE ss.session_id=? ORDER BY ss.position,s.title COLLATE NOCASE,s.id').bind(id).all()).results}
export async function sessionState(id:string){const session=await sessionById(id);if(!session)return null;const current=session.nowSongId?await db().prepare("SELECT s.id,s.title,s.artist,s.lyrics,s.lyrics_approved FROM songs s JOIN session_songs ss ON ss.song_id=s.id WHERE ss.session_id=? AND s.id=? AND ss.status='playing'").bind(id,session.nowSongId).first<any>():null;return {session,now:current?{song:current.title,artist:current.artist,songId:current.id,lyrics:current.lyrics_approved?current.lyrics:''}:{song:'',artist:'',songId:null,lyrics:''}}}
export async function links(){const row=await db().prepare("SELECT value FROM settings WHERE key='links'").first<{value:string}>();const values={...defaultLinks,...(row?JSON.parse(row.value):{})};if(!values.whatsapp||/wa\.me\/\d/.test(values.whatsapp))values.whatsapp=defaultLinks.whatsapp;return values}
export async function live(eventId:string|null=null){await provision();const active=await activeId(),id=eventId||active;const state=id?await sessionState(id):null;const visible=state&&!state.session.archived&&id===active;return {settings:{...await links(),requestsOpen:!!(visible&&state.session.requestsOpen)},session:state?{id:state.session.id,name:state.session.name,date:state.session.date,mode:state.session.mode,venue:state.session.venue,city:state.session.city,featuredOriginal:null,isActive:!!visible,archived:!!state.session.archived}:null,eventMissing:!!eventId&&!state,now:visible?state.now:{song:'',artist:'',songId:null,lyrics:''},songs:visible?(await db().prepare("SELECT s.id,s.title,s.artist,ss.status,COALESCE(rc.requestCount,0) AS requestCount FROM session_songs ss JOIN songs s ON s.id=ss.song_id LEFT JOIN (SELECT song_id,COUNT(*) AS requestCount FROM requests WHERE session_id=? GROUP BY song_id) rc ON rc.song_id=s.id WHERE ss.session_id=? AND ss.status IN ('available','reserved','playing') ORDER BY s.title COLLATE NOCASE,s.id").bind(id,id).all()).results:[]}}
export async function allSongs(){return (await db().prepare('SELECT id,title,artist,status,lyrics,lyrics_approved AS lyricsApproved,revision FROM songs ORDER BY title COLLATE NOCASE,id').all()).results}
export async function admin(){const user=await getChatGPTUser();const allowed=(env as any).ADMIN_EMAIL?.trim().toLowerCase();return !!(allowed&&user?.email.toLowerCase()===allowed)}
export function json(data:any,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
export function sameOrigin(r:Request){return r.headers.get('origin')===new URL(r.url).origin}
export async function save(key:string,value:any){return db().prepare('INSERT INTO settings(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,JSON.stringify(value)).run()}
export function reportError(route:string,error:unknown){console.error(route,error instanceof Error?error.message:'Unexpected error')}
