import {db,sessionById,activeId,json} from './data';
import {modes} from './operations';
import {songStates} from './catalog';
export async function sessionCommand(b:any){const d=db();if(b.action==='session_create'){if(b.mode!==undefined&&!modes.includes(b.mode))return json({error:'invalid'},400);if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100||typeof b.date!=='string'||(b.date&&!/^\d{4}-\d{2}-\d{2}$/.test(b.date)))return json({error:'invalid'},400);if(b.date&&new Date(b.date+'T12:00:00Z').toISOString().slice(0,10)!==b.date)return json({error:'invalid'},400);const id=crypto.randomUUID();await d.batch([d.prepare('INSERT INTO sessions(id,name,date,created,mode) VALUES (?,?,?,?,?)').bind(id,b.name.trim(),b.date,Date.now(),b.mode||'concert'),d.prepare("INSERT INTO session_songs(session_id,song_id,status,position) SELECT ?,id,CASE WHEN status='hidden' THEN 'hidden' ELSE 'available' END,rowid FROM songs").bind(id)]);return json({ok:true,sessionId:id})}
if(!['session_mode','session_activate','session_archive','session_rename','session_sync','song_state','break','pause','setlist_add','setlist_remove','setlist_order','clear','status'].includes(b.action))return null;
if(typeof b.sessionId!=='string')return json({error:'invalid'},400);const session=await sessionById(b.sessionId);if(!session)return json({error:'missing_session'},404);if(!Number.isInteger(b.sessionRevision)||session.revision!==b.sessionRevision)return json({error:'conflict'},409);if(session.archived&&b.action!=='session_archive')return json({error:'archived'},409);
const params=[b.sessionId,b.sessionRevision];const guard='EXISTS(SELECT 1 FROM sessions WHERE id=? AND revision=?'+(b.action==='song_state'&&b.status==='playing'?" AND id=(SELECT json_extract(value,'$') FROM settings WHERE key='active_session')":'')+')';const list:D1PreparedStatement[]=[];
if(b.action==='session_activate'){if(typeof b.expectedActiveId!=='string'&&b.expectedActiveId!==null)return json({error:'invalid'},400);if(await activeId()!==b.expectedActiveId)return json({error:'conflict'},409);const result=await d.prepare("UPDATE settings SET value=? WHERE key='active_session' AND value=? AND "+guard).bind(JSON.stringify(b.sessionId),JSON.stringify(b.expectedActiveId),...params).run();return json(result.meta.changes?{ok:true}:{error:'conflict'},result.meta.changes?200:409)}
if(b.action==='session_mode'){if(!modes.includes(b.mode))return json({error:'invalid'},400);list.push(d.prepare('UPDATE sessions SET mode=? WHERE id=? AND revision=?').bind(b.mode,...params))}
if(b.action==='session_rename'){if(typeof b.name!=='string'||!b.name.trim()||b.name.length>100)return json({error:'invalid'},400);list.push(d.prepare('UPDATE sessions SET name=? WHERE id=? AND revision=?').bind(b.name.trim(),...params))}
if(b.action==='session_archive'){if(typeof b.archived!=='boolean')return json({error:'invalid'},400);if(b.archived){list.push(d.prepare("UPDATE settings SET value='null' WHERE key='active_session' AND json_extract(value,'$')=? AND "+guard).bind(b.sessionId,...params));list.push(d.prepare("UPDATE requests SET status='played' WHERE session_id=? AND song_id IN (SELECT song_id FROM session_songs WHERE session_id=? AND status='playing') AND "+guard).bind(b.sessionId,b.sessionId,...params));list.push(d.prepare("UPDATE session_songs SET status='played' WHERE session_id=? AND status='playing' AND "+guard).bind(b.sessionId,...params))}list.push(d.prepare('UPDATE sessions SET archived=?,requests_open=0,now_song_id=NULL WHERE id=? AND revision=?').bind(b.archived?1:0,...params))}
if(b.action==='session_sync')list.push(d.prepare("INSERT OR IGNORE INTO session_songs(session_id,song_id,status,position) SELECT ?,id,CASE WHEN status='hidden' THEN 'hidden' ELSE 'available' END,rowid FROM songs WHERE "+guard).bind(b.sessionId,...params));
if(['song_state','setlist_add','setlist_remove'].includes(b.action)){if(typeof b.id!=='string'||!await d.prepare('SELECT song_id FROM session_songs WHERE session_id=? AND song_id=?').bind(b.sessionId,b.id).first())return json({error:'missing_song'},404)}
if(b.action==='song_state'){if(!songStates.includes(b.status))return json({error:'invalid'},400);if(b.status==='playing'&&await activeId()!==b.sessionId)return json({error:'not_active'},409);if(b.status==='playing'){
list.push(d.prepare("UPDATE requests SET status='played' WHERE session_id=? AND song_id IN (SELECT song_id FROM session_songs WHERE session_id=? AND status='playing' AND song_id<>?) AND "+guard).bind(b.sessionId,b.sessionId,b.id,...params));
list.push(d.prepare("UPDATE session_songs SET status='played' WHERE session_id=? AND status='playing' AND song_id<>? AND "+guard).bind(b.sessionId,b.id,...params));
list.push(d.prepare('UPDATE sessions SET now_song_id=? WHERE id=? AND '+guard).bind(b.id,b.sessionId,...params));
}else{list.push(d.prepare('UPDATE sessions SET now_song_id=NULL WHERE now_song_id=? AND id=? AND revision=?').bind(b.id,...params));if(b.status==='played')list.push(d.prepare("UPDATE requests SET status='played' WHERE session_id=? AND song_id=? AND "+guard).bind(b.sessionId,b.id,...params))}
if(b.status==='reserved')list.push(d.prepare('UPDATE session_songs SET position=(SELECT COALESCE(MAX(position),0)+1 FROM session_songs WHERE session_id=?),in_setlist=1 WHERE session_id=? AND song_id=? AND in_setlist=0 AND '+guard).bind(b.sessionId,b.sessionId,b.id,...params));
list.push(d.prepare('UPDATE session_songs SET status=? WHERE session_id=? AND song_id=? AND '+guard).bind(b.status,b.sessionId,b.id,...params))}
if(b.action==='break'){list.push(d.prepare("UPDATE requests SET status='played' WHERE session_id=? AND song_id IN (SELECT song_id FROM session_songs WHERE session_id=? AND status='playing') AND "+guard).bind(b.sessionId,b.sessionId,...params),d.prepare("UPDATE session_songs SET status='played' WHERE session_id=? AND status='playing' AND "+guard).bind(b.sessionId,...params),d.prepare('UPDATE sessions SET now_song_id=NULL WHERE id=? AND revision=?').bind(...params))}
if(b.action==='pause'){if(typeof b.open!=='boolean')return json({error:'invalid'},400);list.push(d.prepare('UPDATE sessions SET requests_open=? WHERE id=? AND revision=?').bind(b.open?1:0,...params))}
if(b.action==='setlist_add')list.push(d.prepare('UPDATE session_songs SET in_setlist=1,position=(SELECT COALESCE(MAX(position),0)+1 FROM session_songs WHERE session_id=?) WHERE session_id=? AND song_id=? AND in_setlist=0 AND '+guard).bind(b.sessionId,b.sessionId,b.id,...params));
if(b.action==='setlist_remove')list.push(d.prepare('UPDATE session_songs SET in_setlist=0 WHERE session_id=? AND song_id=? AND '+guard).bind(b.sessionId,b.id,...params));
if(b.action==='setlist_order'){if(!Array.isArray(b.ids)||b.ids.length>5000||b.ids.some((id:any)=>typeof id!=='string'))return json({error:'invalid'},400);const current=(await d.prepare('SELECT song_id FROM session_songs WHERE session_id=? AND in_setlist=1').bind(b.sessionId).all<{song_id:string}>()).results.map(r=>r.song_id);if(new Set(b.ids).size!==b.ids.length||current.length!==b.ids.length||!current.every(id=>b.ids.includes(id)))return json({error:'conflict'},409);for(let i=0;i<b.ids.length;i++)list.push(d.prepare('UPDATE session_songs SET position=? WHERE session_id=? AND song_id=? AND '+guard).bind(i+1,b.sessionId,b.ids[i],...params))}
if(b.action==='clear')list.push(d.prepare('DELETE FROM requests WHERE session_id=? AND '+guard).bind(b.sessionId,...params));
if(b.action==='status'){if(!['pending','played'].includes(b.status)||typeof b.id!=='string')return json({error:'invalid'},400);if(!await d.prepare('SELECT id FROM requests WHERE id=? AND session_id=?').bind(b.id,b.sessionId).first())return json({error:'missing'},404);list.push(d.prepare('UPDATE requests SET status=? WHERE id=? AND session_id=? AND '+guard).bind(b.status,b.id,b.sessionId,...params))}
list.push(d.prepare('UPDATE sessions SET revision=revision+1 WHERE id=? AND '+guard).bind(b.sessionId,...params));const result=await d.batch(list);return json(result.at(-1)?.meta.changes?{ok:true}:{error:'conflict'},result.at(-1)?.meta.changes?200:409)}
