"use client";
import {useEffect,useRef,useState} from 'react';
import {useAdmin} from '../language';
export function ArtworkEditor({song,busy,close}:any){
  const t=useAdmin(),[artMessage,AM]=useState(''),[artBusy,AB]=useState(false),[artState,AS]=useState<'checking'|'present'|'absent'|'error'>('checking'),lock=useRef(false);
  const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus();},[]);
  async function checkArtwork(signal:AbortSignal){AS('checking');try{const r=await fetch('/api/song-artwork?id='+encodeURIComponent(song.id),{signal});await r.body?.cancel();if(signal.aborted)return;AS(r.ok?'present':r.status===404?'absent':'error');}catch{if(!signal.aborted||signal.reason?.name==='TimeoutError')AS('error');}}
  useEffect(()=>{const controller=new AbortController();void checkArtwork(AbortSignal.any([controller.signal,AbortSignal.timeout(15000)]));return()=>controller.abort();},[song.id]);
  async function artwork(file?:File){if(lock.current)return;lock.current=true;AB(true);AM('');try{if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1024*1024))throw Error();const r=await fetch('/api/song-artwork?id='+encodeURIComponent(song.id),{signal:AbortSignal.timeout(15000),method:file?'PUT':'DELETE',...(file?{headers:{'Content-Type':file.type},body:file}:{})});const data:any=await r.json();if(!r.ok||data.ok!==true)throw Error();AS(file?'present':'absent');AM(t('Capa guardada/removida.','Artwork saved/removed.'));}catch{AM(t('Não foi possível confirmar. Usa JPG, PNG ou WebP até 1 MB e tenta novamente.','Could not confirm. Use JPG, PNG or WebP up to 1 MB and retry.'));}finally{lock.current=false;AB(false);}}
  return <section className="editor"><h2 ref={heading} tabIndex={-1}>{t('Capa da música','Song artwork')} · {song.title}</h2><button type="button" disabled={busy||artBusy} onClick={close}>{t('Fechar','Close')}</button>
    <h3>{t('Capa opcional','Optional artwork')}</h3><p>{t('JPG, PNG ou WebP até 1 MB.','JPG, PNG or WebP up to 1 MB.')}</p>{artState==='present'?<a className="artwork-preview" target="_blank" rel="noopener noreferrer" href={'/api/song-artwork?id='+encodeURIComponent(song.id)}><img src={'/api/song-artwork?id='+encodeURIComponent(song.id)} width={64} height={64} alt="" loading="lazy" onError={()=>AS('error')}/>{t('Ver capa guardada ↗','View saved artwork ↗')}</a>:<p role="status">{artState==='checking'?t('A verificar capa…','Checking artwork…'):artState==='absent'?t('Sem capa. Podes adicionar uma quando quiseres.','No artwork. You can add one whenever you like.'):t('Não foi possível verificar a capa.','Could not check artwork.')}</p>}{artState==='error'&&<button disabled={busy||artBusy} onClick={()=>void checkArtwork(AbortSignal.timeout(15000))}>{t('Verificar novamente','Check again')}</button>}<label>{t('Enviar/substituir capa','Upload/replace artwork')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||artBusy||artState==='checking'} onChange={e=>{const f=e.target.files?.[0];if(f)void artwork(f);e.target.value='';}}/></label><button disabled={busy||artBusy||artState!=='present'} onClick={()=>{if(confirm(t('Remover a capa desta música?','Remove this song’s artwork?')))void artwork();}}>{t('Remover capa','Remove artwork')}</button><p role="status">{artBusy?t('A guardar…','Saving…'):artMessage}</p>
  </section>;
}
