"use client";
import {useEffect,useRef,useState} from 'react';
import {useAdmin} from '../language';
export function MetadataEditor({song,busy,save,close}:any){
  const t=useAdmin(),[draft,D]=useState({...song}),[artMessage,AM]=useState(''),[artBusy,AB]=useState(false),[artState,AS]=useState<'checking'|'present'|'absent'|'error'>('checking'),lock=useRef(false);
  const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus();},[]);
  async function checkArtwork(signal:AbortSignal){AS('checking');try{const r=await fetch('/api/song-artwork?id='+encodeURIComponent(song.id),{signal});await r.body?.cancel();if(signal.aborted)return;AS(r.ok?'present':r.status===404?'absent':'error');}catch{if(!signal.aborted||signal.reason?.name==='TimeoutError')AS('error');}}
  useEffect(()=>{const controller=new AbortController();void checkArtwork(AbortSignal.any([controller.signal,AbortSignal.timeout(15000)]));return()=>controller.abort();},[song.id]);
  async function artwork(file?:File){if(lock.current)return;lock.current=true;AB(true);AM('');try{if(file&&(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1024*1024))throw Error();const r=await fetch('/api/song-artwork?id='+encodeURIComponent(song.id),{signal:AbortSignal.timeout(15000),method:file?'PUT':'DELETE',...(file?{headers:{'Content-Type':file.type},body:file}:{})});const data:any=await r.json();if(!r.ok||data.ok!==true)throw Error();AS(file?'present':'absent');AM(t('Capa guardada/removida.','Artwork saved/removed.'));}catch{AM(t('Não foi possível confirmar. Usa JPG, PNG ou WebP até 1 MB e tenta novamente.','Could not confirm. Use JPG, PNG or WebP up to 1 MB and retry.'));}finally{lock.current=false;AB(false);}}
  return <section className="editor"><h2 ref={heading} tabIndex={-1}>{t('Metadados globais','Global metadata')} · {song.title}</h2><p>{t('Partilhados por todos os eventos. Campos opcionais.','Shared by all events. All fields optional.')}</p><form onSubmit={e=>{e.preventDefault();save({action:'metadata',id:song.id,revision:song.revision,metadata:{genre:draft.genre||'',decade:draft.decade===''||draft.decade==null?null:Number(draft.decade),language:draft.language||'',mood:draft.mood||'',recommended:Number(draft.recommended)||0}});}}>
    <div className="management-fields">{[['genre',t('Género','Genre')],['language',t('Idioma (pt, en…)','Language (pt, en…)')],['mood',t('Ambiente','Mood')]].map(([k,label])=><label key={k}>{label}<input disabled={busy} maxLength={k==='language'?35:80} value={draft[k]||''} onChange={e=>D({...draft,[k]:e.target.value})}/></label>)}<label>{t('Década','Decade')}<input disabled={busy} type="number" min={1900} max={2100} step={10} value={draft.decade??''} onChange={e=>D({...draft,decade:e.target.value})}/></label><label>{t('Recomendada','Recommended')}<select disabled={busy} value={draft.recommended||0} onChange={e=>D({...draft,recommended:Number(e.target.value)})}><option value={0}>{t('Não','No')}</option><option value={1}>{t('Sim','Yes')}</option></select></label></div><button disabled={busy||artBusy}>{t('Guardar metadados','Save metadata')}</button><button type="button" disabled={busy||artBusy} onClick={close}>{t('Fechar','Close')}</button></form>
    <h3>{t('Capa opcional','Optional artwork')}</h3><p>{t('JPG, PNG ou WebP até 1 MB. Ainda não aparece no público.','JPG, PNG or WebP up to 1 MB. Not displayed publicly yet.')}</p>{artState==='present'?<a target="_blank" rel="noopener noreferrer" href={'/api/song-artwork?id='+encodeURIComponent(song.id)}>{t('Ver capa guardada ↗','View saved artwork ↗')}</a>:<p role="status">{artState==='checking'?t('A verificar capa…','Checking artwork…'):artState==='absent'?t('Sem capa. Podes adicionar uma quando quiseres.','No artwork. You can add one whenever you like.'):t('Não foi possível verificar a capa.','Could not check artwork.')}</p>}{artState==='error'&&<button disabled={busy||artBusy} onClick={()=>void checkArtwork(AbortSignal.timeout(15000))}>{t('Verificar novamente','Check again')}</button>}<label>{t('Enviar/substituir capa','Upload/replace artwork')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||artBusy||artState==='checking'} onChange={e=>{const f=e.target.files?.[0];if(f)void artwork(f);e.target.value='';}}/></label><button disabled={busy||artBusy||artState!=='present'} onClick={()=>{if(confirm(t('Remover a capa desta música?','Remove this song’s artwork?')))void artwork();}}>{t('Remover capa','Remove artwork')}</button><p role="status">{artBusy?t('A guardar…','Saving…'):artMessage}</p>
  </section>;
}
export function EventEditor({session,busy,save}:any){const t=useAdmin(),[draft,D]=useState({venue:session.venue||'',city:session.city||'',featured_title:session.featuredTitle||'',featured_artist:session.featuredArtist||'',featured_url:session.featuredUrl||''}),[name,N]=useState(''),[date,Date]=useState('');return <section><h2>{t('Contexto do evento','Event context')}</h2><form onSubmit={e=>{e.preventDefault();save({action:'event_metadata',metadata:draft});}}><div className="management-fields">{[['venue',t('Local','Venue')],['city',t('Cidade','City')],['featured_title',t('Original: título','Original: title')],['featured_artist',t('Original: artista','Original: artist')],['featured_url',t('Original: URL HTTPS','Original: HTTPS URL')]].map(([k,label])=><label key={k}>{label}<input type={k==='featured_url'?'url':'text'} maxLength={k==='featured_url'?2000:k==='venue'?160:k==='city'?100:140} disabled={busy||session.archived} value={(draft as any)[k]} onChange={e=>D({...draft,[k]:e.target.value})}/></label>)}</div><p>{t('Original: preencher os três campos ou deixar todos vazios.','Original: complete all three fields or leave all empty.')}</p><button disabled={busy||session.archived}>{t('Guardar contexto','Save context')}</button></form><h3>{t('Duplicar para preparar outro evento','Duplicate to prepare another event')}</h3><p>{t('Copia contexto, repertório e alinhamento. Sem pedidos/tips, sem ativar; pedidos pausados. A tocar/tocadas voltam a disponíveis.','Copies context, repertoire and setlist. No requests/tips, no activation; requests paused. Playing/played songs become available.')}</p><form onSubmit={e=>{e.preventDefault();if(confirm(t('Criar a cópia inativa deste evento?','Create an inactive copy of this event?')))save({action:'duplicate',name,date});}}><label>{t('Nome do novo evento','New event name')}<input required maxLength={100} disabled={busy} value={name} onChange={e=>N(e.target.value)}/></label><label>{t('Data (opcional)','Date (optional)')}<input type="date" disabled={busy} value={date} onChange={e=>Date(e.target.value)}/></label><button disabled={busy}>{t('Criar cópia','Create copy')}</button></form></section>;}
