"use client";
import {useEffect,useRef,useState} from 'react';
import {useAdmin} from '../language';
import {filterManagement} from '../../advanced-management';
import {MetadataEditor,EventEditor} from './editors';
const empty={q:'',genre:'',decade:'',language:'',recommended:'',status:''};
export default function Management(){
  const t=useAdmin(),[data,D]=useState<any>(null),[sessionId,SI]=useState(''),[scope,S]=useState('event'),[filters,F]=useState(empty),[page,P]=useState(0),[selected,Select]=useState<string[]>([]),[edit,E]=useState<any>(null),[busy,B]=useState(false),[error,Error]=useState(''),[ready,R]=useState(false),[loading,L]=useState(false);
  const lock=useRef(false),generation=useRef(0);
  async function load(id:string){const g=++generation.current;R(false);L(true);try{const r=await fetch('/api/management'+(id?'?sessionId='+encodeURIComponent(id):''),{signal:AbortSignal.timeout(15000)}),v:any=await r.json();if(!r.ok||!Array.isArray(v.catalog)||!v.session)throw new globalThis.Error();if(g===generation.current){D(v);R(true);}}catch{if(g===generation.current)Error(t('Não foi possível atualizar os dados. Tenta novamente.','Could not refresh data. Please retry.'));}finally{if(g===generation.current)L(false);}}
  useEffect(()=>{void load(sessionId);return()=>{generation.current++;};},[sessionId]);
  function reset(){Select([]);P(0);E(null);}
  async function act(command:any){if(lock.current||!ready)return;lock.current=true;B(true);Error('');try{const r=await fetch('/api/management',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:data.session.id,sessionRevision:data.session.revision,...command}),signal:AbortSignal.timeout(15000)}),v:any=await r.json();if(!r.ok||v.ok!==true){Error(v.error==='conflict'?t('Os dados mudaram, o evento está arquivado ou a seleção inclui uma música a tocar. Confere os dados atualizados.','Data changed, the event is archived or the selection includes a playing song. Check refreshed data.'):t('Não foi possível guardar. Verifica os campos e tenta novamente.','Could not save. Check the fields and retry.'));await load(data.session.id);return;}
      Error(t('Guardado.','Saved.'));if(v.sessionId){SI(v.sessionId);await load(v.sessionId);}else await load(data.session.id);reset();
    }catch{R(false);Error(t('Resultado não confirmado. Atualiza e verifica antes de repetir, sobretudo uma duplicação.','Result unconfirmed. Refresh and check before repeating, especially duplication.'));}finally{lock.current=false;B(false);}}
  const stateNames:Record<string,string>={outside:t('Fora do evento','Outside event'),available:t('Disponível para pedidos','Available for requests'),reserved:t('Reservada','Reserved'),playing:t('A tocar','Playing'),played:t('Tocada','Played'),hidden:t('Oculta no evento','Hidden in event')};
  const eventMap=new Map<string,any>((data?.eventSongs||[]).map((s:any)=>[s.id,s]));
  const rows=(data?.catalog||[]).map((s:any)=>({...s,status:eventMap.get(s.id)?.status||'outside'})).filter((s:any)=>scope==='global'||s.status!=='outside');
  const matches=filterManagement(rows,filters),last=Math.max(0,Math.ceil(matches.length/20)-1),current=Math.min(page,last),visible=matches.slice(current*20,current*20+20),disabled=busy||!ready;
  function bulk(action:string,status?:string){if(!selected.length)return;const eligible=selected.every(id=>action==='add'||eventMap.has(id));if(!eligible){Error(t('Seleciona apenas músicas do evento para esta ação.','Select only event songs for this action.'));return;}const operation=action==='add'?t('Adicionar ao evento','Add to event'):action==='remove'?t('Remover do evento','Remove from event'):status==='available'?t('Disponibilizar pedidos','Make available for requests'):t('Indisponibilizar pedidos','Make unavailable for requests');if(confirm(operation+' — '+selected.length+t(' músicas selecionadas? Não altera pedidos históricos.',' selected songs? Historical requests are unchanged.')))void act({action,ids:selected,status});}
  return <main className="admin advanced"><a href="/admin">{t('← Gestão completa','← Full management')}</a><h1>{t('Catálogo e eventos','Catalogue and events')}</h1><div className="management-feedback"><p role="status" tabIndex={0}>{busy?t('A guardar…','Saving…'):loading?t('A atualizar…','Refreshing…'):error}</p><button disabled={busy||loading} onClick={()=>{Error('');void load(data?.session.id||sessionId);}}>{t('Atualizar','Refresh')}</button></div>{!data?(!error&&<p>{t('A carregar…','Loading…')}</p>):<>
    <label>{t('Evento de trabalho','Working event')}<select disabled={busy} value={data.session.id} onChange={e=>{reset();F(empty);D(null);SI(e.target.value);}}>{data.sessions.map((s:any)=><option key={s.id} value={s.id}>{s.name}{s.archived?t(' · arquivado',' · archived'):''}</option>)}</select></label>
    <p>{data.session.archived?t('Evento arquivado','Archived event'):data.activeSessionId!==data.session.id?t('Evento inativo · sem pedidos públicos','Inactive event · no public requests'):data.session.requestsOpen?t('Evento ativo · pedidos abertos','Active event · requests open'):t('Evento ativo · pedidos pausados','Active event · requests paused')}</p>
    <p>{t('O catálogo global é partilhado. O repertório pertence a este evento. Apenas músicas disponíveis num evento ativo com pedidos abertos podem ser pedidas.','The global catalogue is shared. The repertoire belongs to this event. Only available songs in an active event with requests open can be requested.')}</p>
    <label>{t('Vista','View')}<select disabled={busy} value={scope} onChange={e=>{S(e.target.value);F(empty);reset();}}><option value="global">{t('Catálogo global','Global catalogue')}</option><option value="event">{t('Repertório do evento','Event repertoire')}</option></select></label>
    <div className="management-fields"><label>{t('Pesquisar título ou artista','Search title or artist')}<input type="search" value={filters.q} onChange={e=>{F({...filters,q:e.target.value});reset();}}/></label>
    {(['genre','decade','language'] as const).map(k=>{const options=[...new Set<string>(rows.map((s:any)=>String(s[k]??'')).filter(Boolean))].sort();return options.length?<label key={k}>{k==='genre'?t('Género','Genre'):k==='decade'?t('Década','Decade'):t('Idioma','Language')}<select value={filters[k]} onChange={e=>{F({...filters,[k]:e.target.value});reset();}}><option value="">{t('Todos','All')}</option>{options.map(v=><option key={v}>{v}</option>)}</select></label>:null;})}
    <label>{t('Recomendada','Recommended')}<select value={filters.recommended} onChange={e=>{F({...filters,recommended:e.target.value});reset();}}><option value="">{t('Todas','All')}</option><option value="1">{t('Sim','Yes')}</option><option value="0">{t('Não','No')}</option></select></label><label>{t('Estado neste evento','Status in this event')}<select value={filters.status} onChange={e=>{F({...filters,status:e.target.value});reset();}}><option value="">{t('Todos','All')}</option>{Object.entries(stateNames).filter(([key])=>scope==='global'||key!=='outside').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label></div>
    <p>{matches.length} {t('resultados','results')} · {selected.length}/40 {t('selecionadas','selected')}</p><div className="management-actions"><button disabled={disabled} onClick={()=>Select(visible.map(s=>s.id))}>{t('Selecionar esta página','Select this page')}</button><button disabled={disabled||!selected.length} onClick={()=>Select([])}>{t('Limpar seleção','Clear selection')}</button>{[['add',t('Adicionar ao evento','Add to event')],['remove',t('Remover do evento','Remove from event')],['available',t('Disponibilizar pedidos','Make requestable')],['hidden',t('Ocultar dos pedidos','Hide from requests')]].map(([action,label])=><button key={action} disabled={disabled||!selected.length||data.session.archived} onClick={()=>bulk(['available','hidden'].includes(action)?'availability':action,['available','hidden'].includes(action)?action:undefined)}>{label}</button>)}</div>
    <ul className="management-list">{visible.map(song=><li key={song.id}><label className="management-check"><input type="checkbox" checked={selected.includes(song.id)} disabled={disabled||!selected.includes(song.id)&&selected.length>=40} onChange={e=>Select(e.target.checked?[...selected,song.id]:selected.filter(id=>id!==song.id))}/><span><strong>{song.title}</strong><small>{song.artist} · {stateNames[song.status]}</small><small>{[song.genre,song.decade,song.language,song.recommended?t('Recomendada','Recommended'):''].filter(Boolean).join(' · ')}</small></span></label><button disabled={disabled} onClick={()=>E(song)}>{t('Metadados / capa','Metadata / artwork')}</button></li>)}</ul>{!matches.length&&<p>{t('Sem resultados.','No results.')}</p>}<nav className="management-actions" aria-label={t('Paginação','Pagination')}><button disabled={current===0} onClick={()=>P(current-1)}>{t('Anterior','Previous')}</button><span>{current+1} / {last+1}</span><button disabled={current===last} onClick={()=>P(current+1)}>{t('Seguinte','Next')}</button></nav>
    {edit&&<MetadataEditor key={edit.id+':'+edit.revision} song={edit} busy={disabled} save={act} close={()=>E(null)}/>}
    <EventEditor key={data.session.id+':'+data.session.revision} session={data.session} busy={disabled} save={act}/>
  </>}</main>;
}
